SELECT * FROM (
    SELECT 
        ap.AIRPORTNAME,
        ap.AIRPORTCITY,
        ap.AIRPORTCOUNTRY,
        COUNT(*) AS TOTAL_FLIGHTS
    FROM 
        AIRPORTS ap
    JOIN FLIGHTSGOING fg 
        ON ap.AIRPORTID = fg.DEPARTUREAIRPORTID 
        OR ap.AIRPORTID = fg.ARRIVALAIRPORTID
    GROUP BY 
        ap.AIRPORTNAME, ap.AIRPORTCITY, ap.AIRPORTCOUNTRY
    ORDER BY 
        TOTAL_FLIGHTS DESC
)
WHERE ROWNUM <= 5;