SELECT * FROM (
    SELECT 
        al.AIRLINENAME,
        COUNT(fg.FLIGHTSGOINGID) AS TOTAL_FLIGHTS,
        ROUND(AVG(fg.DESTINATIONDISTANCE), 2) AS AVG_DISTANCE
    FROM 
        AIRLINES al
    JOIN AIRLINESAEROPLANES aa ON al.AIRLINEID = aa.AIRLINEID
    JOIN FLIGHTSGOING fg ON aa.AIRLINESAEROPLANESID = fg.AIRLINESAEROPLANESID
    GROUP BY 
        al.AIRLINENAME
    HAVING 
        AVG(fg.DESTINATIONDISTANCE) > (
            SELECT AVG(DESTINATIONDISTANCE)
            FROM FLIGHTSGOING
        )
    ORDER BY 
        AVG_DISTANCE DESC
)
WHERE ROWNUM <= 5;